website/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_bcrypt import check_password_hash
from flask_login import login_user, logout_user, login_required, current_user

from website import bcrypt, db
from website.enums import JobRoles, Skills
from website.forms import RegistrationForm, LoginForm, UpdateUserForm, SearchUSerForm
from website.models import User, Job

main = Blueprint("main", __name__)


@main.route("/")
@main.route("/home", methods=["GET", "POST"])
@login_required
def home():
    form = UpdateUserForm()
    if form.validate_on_submit():
        user = User.query.filter_by(id=current_user.id).first()
        update_user(user)
    return render_template(
        "home.html",
        user=current_user,
        job_roles=JobRoles,
        jobs=Job.query.all(),
        is_home=True,
        skills=Skills,
        form=form,
    )


@main.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user:
            flash("Email already registered", "error")
            return redirect(url_for("main.register"))

        encrypted_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        new_user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            password=encrypted_password,
        )
        db.session.add(new_user)
        db.session.commit()
        flash(
            "You have successfully registered! You can now log in", category="success"
        )
        return redirect(url_for("main.login"))
    return render_template("register.html", form=form)


@main.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user:
            if check_password_hash(existing_user.password, form.password.data):
                login_user(existing_user)
                return redirect(url_for("main.home"))
            else:
                flash("Incorrect password", category="error")
        else:
            flash("Incorrect email", category="error")
    return render_template("login.html", form=form)


@main.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.login"))


@main.route("/view-record/<int:user_id>/delete", methods=["POST"])
def delete_user(user_id: int):
    user = User.query.get_or_404(user_id)
    if user == current_user:
        flash(
            "Sorry you cannot delete your own account. Another admin will have to do this for you.",
            "error",
        )
        return redirect(url_for("main.view_record", user_id=user_id))
    else:
        db.session.delete(user)
        db.session.commit()
        flash("User has been deleted.", "success")
        return redirect(url_for("main.view_users"))


@main.route("/view-users", methods=["GET", "POST"])
def view_users():
    if not current_user.is_admin:
        flash("Please log in as an administrator to view this page", "error")
        return redirect(url_for("main.login"))
    return render_template("view-users.html", users=User.query.all())


@main.route("/search-users", methods=["GET", "POST"])
def search_users():
    form = SearchUSerForm()
    if not current_user.is_admin:
        flash("Please log in as an administrator to view this page", "error")
        return redirect(url_for("main.login"))
    # There is no form validation necessary here as the inputs are selection of set skill values which come from the Skills enum
    if request.method == "POST":
        # Using a ternary operator here to convert null values to empty strings
        skill_1 = request.form["skill_1"] if request.form["skill_1"] else ""
        skill_2 = request.form["skill_2"] if request.form["skill_2"] else ""
        skill_3 = request.form["skill_3"] if request.form["skill_3"] else ""
        filtered_users = []
        for user in User.query.all():
            # Converting the skills to empty strings means the __contains__ method below will still return true when no value is entered
            # This allows the user to leave empty fields in the search
            if (
                    user.__str__().__contains__(skill_1)
                    and user.__str__().__contains__(skill_2)
                    and user.__str__().__contains__(skill_3)
            ):
                filtered_users.append(user)
        if filtered_users.__len__() == 0:
            flash("Sorry there are no users with those skills", category="error")
        else:
            return render_template(
                "search-users.html", skills=Skills, users=filtered_users, form=form
            )
    return render_template("search-users.html", skills=Skills, form=form)


@main.route("/view-record/<int:user_id>/update", methods=["GET", "POST"])
def view_record(user_id: int):
    form = UpdateUserForm()
    user = User.query.filter_by(id=user_id).first()
    if request.method == "POST":
        update_user(user)
        return redirect(url_for("main.view_record", user_id=user_id))
    return render_template(
        "home.html",
        user=user,
        job_roles=JobRoles,
        jobs=Job.query.all(),
        is_home=False,
        skills=Skills,
        form=form,
    )

# function to update User record with input from HTML form on the home page
def update_user(user):
    user_fields = [
        "first_name",
        "last_name",
        "email",
        "contact_number",
        "skill_1",
        "skill_2",
        "skill_3",
    ]
    for field in user_fields:
        new_value = request.form[field]
        if new_value:
            setattr(user, field, new_value)
    job_title = request.form["job_title"]
    # We find the job id for the given job title and add this to our User record
    if job_title:
        job = Job.query.filter_by(job_title=job_title).first()
        job_id = job.id
        user.job_id = job_id
    db.session.commit()

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
              integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
              crossorigin="anonymous" />
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
              crossorigin="anonymous" />
        <title>
            {% block title %}Home{% endblock %}
        </title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">EmployeeLookup</a>
                <button class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbar"
                        aria-controls="navbarNav"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbar">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a {% block home %}class="nav-link active"{% endblock %} href="/">Home</a>
                        </li>
                        {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="/logout">Logout</a>
                            </li>
                            {% if current_user.is_admin %}
                                <li class="nav-item">
                                    <a {% block admin %}class="nav-link"{% endblock %} href="/view-users">ViewUsers</a>
                                </li>
                                <li class="nav-item">
                                    <a {% block search_users %}class="nav-link"{% endblock %}
                                       href="/search-users">SearchUsers</a>
                                </li>
                            {% endif %}
                        {% else %}
                            <li class="nav-item">
                                <a {% block login %}class="nav-link"{% endblock %} href="/login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a {% block register %}class="nav-link"{% endblock %} href="/register">Register</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if
                messages %}
                {% for category, message in messages %}
                    {% if category ==
                        'error' %}
                        <div class="alert alert-danger alter-dismissable fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% else %}
                        <div class="alert alert-success alter-dismissable fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
                integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
                integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
                crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
                crossorigin="anonymous"></script>
    </body>
</html>

website/templates/home.html
{% extends "base.html" %}
{% block content %}
    {% if is_home %}
        <h2 class="text-center p-2">Welcome {{ user.first_name }}!</h2>
        <h3 class="text-center p-2">View and edit your details below</h3>
        <p class="text-center p-2">
            Add values to the fields you wish to change and click submit (empty fields will not
            be
            changed).
        </p>
    {% else %}
        <h2 class="text-center p-2 text-danger">This is an admin area</h2>
        <h3 class="text-center p-2">View and edit employee details below</h3>
    {% endif %}
    <container class="container d-flex flex-column">
        <form method="POST"
                {% if is_home %} action="/home" {% else %}
              action="{{ url_for('main.view_record', user_id=user.id) }}" {% endif %}
              class="d-flex flex-column mb-4">
            {{ form.hidden_tag() }}
            <table class="table table-bordered text-center mx-auto">
                <tr>
                    <td class="table-primary">First Name</td>
                    <td class="table-light">{{ user.first_name }}</td>
                    <td class="table-light">
                        {{ form.first_name(class="validate form-control", placeholder="Enter new first name") }}
                        {% if form.first_name.errors %}
                            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                                {{ form.first_name.errors[0] }}
                                <button type="button" class="close" data-dismiss="alert">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td class="table-primary">Last Name</td>
                    <td class="table-light">{{ user.last_name }}</td>
                    <td class="table-light">
                        {{ form.last_name(class="validate form-control", placeholder="Enter new last name") }}
                        {% if form.last_name.errors %}
                            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                                {{ form.last_name.errors[0] }}
                                <button type="button" class="close" data-dismiss="alert">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td class="table-primary">Email</td>
                    <td class="table-light">{{ user.email }}</td>
                    <td class="table-light">
                        {{ form.email(class="validate form-control", placeholder="Enter new email") }}
                        {% if form.email.errors %}
                            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                                {{ form.email.errors[0] }}
                                <button type="button" class="close" data-dismiss="alert">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td class="table-primary">Phone number</td>
                    <td class="table-light">{{ user.contact_number }}</td>
                    <td class="table-light">
                        {{ form.contact_number(class="validate form-control", placeholder="Enter new phone number") }}
                        {% if form.contact_number.errors %}
                            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                                {{ form.contact_number.errors[0] }}
                                <button type="button" class="close" data-dismiss="alert">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td class="table-primary">Job Role</td>
                    <td class="table-light">{{ user.job.job_title }}</td>
                    <td class="table-light">
                        <select name="job_title" id="job_title" class="form-control"
                                {# Job title can only bed edited by Admin. So we hide it for regular Users. #}
                                {% if is_home %}hidden{% endif %}
                        >
                            <option selected></option>
                            <option>{{ job_roles.SOFTWARE_ENGINEER.value }}</option>
                            <option>{{ job_roles.PRODUCT_MANAGER.value }}</option>
                            <option>{{ job_roles.SENIOR_SOFTWARE_ENGINEER.value }}</option>
                            <option>{{ job_roles.TEAM_MANAGER.value }}</option>
                            <option>{{ job_roles.UX_DESIGNER.value }}</option>
                            <option>{{ job_roles.CHIEF_TECHNOLOGY_OFFICER.value }}</option>
                            <option>{{ job_roles.HUMAN_RESOURCES_MANAGER.value }}</option>
                            <option>{{ job_roles.MARKETING_DIRECTOR.value }}</option>
                            <option>{{ job_roles.IT_SUPPORT_SPECIALIST.value }}</option>
                            <option>{{ job_roles.DATA_ANALYST.value }}</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="table-primary">Base Salary</td>
                    <td class="table-light">{{ user.job.base_salary }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td class="table-primary">Department</td>
                    <td class="table-light">{{ user.job.department }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td class="table-success">Skill 1</td>
                    <td class="table-light">{{ user.skill_1 }}</td>
                    <td class="table-light">
                        <select name="skill_1" id="skill_1" class="form-control">
                            <option selected></option>
                            <option>{{ skills.JAVA.value }}</option>
                            <option>{{ skills.PYTHON.value }}</option>
                            <option>{{ skills.TYPESCRIPT.value }}</option>
                            <option>{{ skills.AWS.value }}</option>
                            <option>{{ skills.GIT.value }}</option>
                            <option>{{ skills.CUSTOMER_SERVICE.value }}</option>
                            <option>{{ skills.PROJECT_MANAGEMENT.value }}</option>
                            <option>{{ skills.GRAPHIC_DESIGN.value }}</option>
                            <option>{{ skills.PHOTOGRAPHY.value }}</option>
                            <option>{{ skills.DATA_ANALYTICS.value }}</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="table-success">Skill 2</td>
                    <td class="table-light">{{ user.skill_2 }}</td>
                    <td class="table-light">
                        <select name="skill_2" id="skill_2" class="form-control">
                            <option selected></option>
                            <option>{{ skills.JAVA.value }}</option>
                            <option>{{ skills.PYTHON.value }}</option>
                            <option>{{ skills.TYPESCRIPT.value }}</option>
                            <option>{{ skills.AWS.value }}</option>
                            <option>{{ skills.GIT.value }}</option>
                            <option>{{ skills.CUSTOMER_SERVICE.value }}</option>
                            <option>{{ skills.PROJECT_MANAGEMENT.value }}</option>
                            <option>{{ skills.GRAPHIC_DESIGN.value }}</option>
                            <option>{{ skills.PHOTOGRAPHY.value }}</option>
                            <option>{{ skills.DATA_ANALYTICS.value }}</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="table-success">Skill 3</td>
                    <td class="table-light">{{ user.skill_3 }}</td>
                    <td class="table-light">
                        <select name="skill_3" id="skill_3" class="form-control">
                            <option selected></option>
                            <option>{{ skills.JAVA.value }}</option>
                            <option>{{ skills.PYTHON.value }}</option>
                            <option>{{ skills.TYPESCRIPT.value }}</option>
                            <option>{{ skills.AWS.value }}</option>
                            <option>{{ skills.GIT.value }}</option>
                            <option>{{ skills.CUSTOMER_SERVICE.value }}</option>
                            <option>{{ skills.PROJECT_MANAGEMENT.value }}</option>
                            <option>{{ skills.GRAPHIC_DESIGN.value }}</option>
                            <option>{{ skills.PHOTOGRAPHY.value }}</option>
                            <option>{{ skills.DATA_ANALYTICS.value }}</option>
                        </select>
                    </td>
                </tr>
            </table>
            <button type="submit" class="btn btn-secondary px-4 mx-auto">Submit</button>
        </form>
        {% if not is_home %}
            <form action="{{ url_for('main.delete_user', user_id=user.id) }}"
                  method="POST"
                  class="mx-auto"
                  onsubmit="event.preventDefault(); confirmDelete(this);">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <button type="submit" class="btn btn-danger px-4">DELETE USER</button>
            </form>
        {% endif %}
    </container>
    <script>
        function confirmDelete(form) {
            const userConfirmation = confirm("Are you sure you want to delete this user?");
            if (userConfirmation) {
                return form.submit();
            } else {
                return false;
            }
        }
    </script>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block login %}class="nav-link active"{% endblock %}
{% block home %}class="nav-link"{% endblock %}
{% block content %}
    <div class="container-sm">
        <form method="POST" action="/login">
            {{ form.hidden_tag() }}
            <h3 class="text-center p-3">Log in</h3>
            <div class="form-group">
                {{ form.email.label() }}
                {{ form.email(class="validate form-control", placeholder="Enter email") }}
                {% if form.email.errors %}
                    <div class="alert alert-danger alter-dismissable fade show" role="alert">
                        {{ form.email.errors[0] }}
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label() }}
                {{ form.password(class="validate form-control", placeholder="Confirm Password") }}
                {% if form.password.errors %}
                    <div class="alert alert-danger alter-dismissable fade show" role="alert">
                        {{ form.password.errors[0] }}
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
            </div>
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-warning m-2 px-4">Log In</button>
            </div>
        </form>
    </div>
{% endblock %}

website/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block register %}class="nav-link active"{% endblock %}
{% block home %}class="nav-link" href="/"{% endblock %}
{% block content %}
    <div class="container-sm">
        <form method="POST" action="{{ url_for("main.register") }}">
            {{ form.hidden_tag() }}
            <h3 class="text-center p-3">Sign up as a new user</h3>
            <div class="form-group">
                {{ form.email.label() }}
                {{ form.email(class="validate form-control", placeholder="Enter email") }}
                {% if form.email.errors %}
                    <div class="alert alert-danger alter-dismissable fade show" role="alert">
                        {{ form.email.errors[0] }}
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.first_name.label() }}
                {{ form.first_name(class="validate form-control", placeholder="Enter First Name") }}
                {% if form.first_name.errors %}
                    <div class="alert alert-danger alter-dismissable fade show" role="alert">
                        {{ form.first_name.errors[0] }}
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.last_name.label() }}
                {{ form.last_name(class="validate form-control", placeholder="Enter Last Name") }}
                {% if form.last_name.errors %}
                    <div class="alert alert-danger alter-dismissable fade show" role="alert">
                        {{ form.last_name.errors[0] }}
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label() }}
                {{ form.password(class="validate form-control", placeholder="Password") }}
                {% if form.password.errors %}
                    <div class="alert alert-danger alter-dismissable fade show" role="alert">
                        {{ form.password.errors[0] }}
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label() }}
                {{ form.confirm_password(class="validate form-control", placeholder="Confirm Password") }}
                {% if form.confirm_password.errors %}
                    <div class="alert alert-danger alter-dismissable fade show" role="alert">
                        {{ form.confirm_password.errors[0] }}
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
            </div>
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-warning m-2 px-4">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}

website/templates/search-users.html
{% extends "base.html" %}
{% block title %}Admin{% endblock %}
{% block search_users %}class="nav-link active"{% endblock %}
{% block home %}class="nav-link"{% endblock %}
{% block content %}
    <h2 class="text-center p-4">Search users</h2>
    <h3 class="text-center p-4">Enter one or more skills</h3>
    <form method="POST" action="/search-users" class="container text-center">
        {{ form.hidden_tag() }}
        <select class="form-select py-2" name="skill_1" id="skill_1">
            <option selected></option>
            <option>{{ skills.JAVA.value }}</option>
            <option>{{ skills.PYTHON.value }}</option>
            <option>{{ skills.TYPESCRIPT.value }}</option>
            <option>{{ skills.AWS.value }}</option>
            <option>{{ skills.GIT.value }}</option>
            <option>{{ skills.CUSTOMER_SERVICE.value }}</option>
            <option>{{ skills.PROJECT_MANAGEMENT.value }}</option>
            <option>{{ skills.GRAPHIC_DESIGN.value }}</option>
            <option>{{ skills.PHOTOGRAPHY.value }}</option>
            <option>{{ skills.DATA_ANALYTICS.value }}</option>
        </select>
        <select class="form-select py-2" name="skill_2" id="skill_2">
            <option selected></option>
            <option>{{ skills.JAVA.value }}</option>
            <option>{{ skills.PYTHON.value }}</option>
            <option>{{ skills.TYPESCRIPT.value }}</option>
            <option>{{ skills.AWS.value }}</option>
            <option>{{ skills.GIT.value }}</option>
            <option>{{ skills.CUSTOMER_SERVICE.value }}</option>
            <option>{{ skills.PROJECT_MANAGEMENT.value }}</option>
            <option>{{ skills.GRAPHIC_DESIGN.value }}</option>
            <option>{{ skills.PHOTOGRAPHY.value }}</option>
            <option>{{ skills.DATA_ANALYTICS.value }}</option>
        </select>
        <select class="form-select py-2" name="skill_3" id="skill_3">
            <option selected></option>
            <option>{{ skills.JAVA.value }}</option>
            <option>{{ skills.PYTHON.value }}</option>
            <option>{{ skills.TYPESCRIPT.value }}</option>
            <option>{{ skills.AWS.value }}</option>
            <option>{{ skills.GIT.value }}</option>
            <option>{{ skills.CUSTOMER_SERVICE.value }}</option>
            <option>{{ skills.PROJECT_MANAGEMENT.value }}</option>
            <option>{{ skills.GRAPHIC_DESIGN.value }}</option>
            <option>{{ skills.PHOTOGRAPHY.value }}</option>
            <option>{{ skills.DATA_ANALYTICS.value }}</option>
        </select>
        <button type="submit" class="btn btn-primary px-4 py-2 mx-auto">Search</button>
    </form>
    <div class="row justify-content-center p-3">
        <div class="col-auto">
            <table class="table table-hover table-responsive">
                {% if users %}
                    <thead>
                    <tr>
                        <th class="table-primary">Id</th>
                        <th class="table-primary">Email</th>
                        <th class="table-primary">First Name</th>
                        <th class="table-primary">Last Name</th>
                        <th class="table-primary">Contact Number</th>
                        <th class="table-primary">Job Title</th>
                        <th colspan="3" class="text-center table-success">Skills</th>
                    </tr>
                    </thead>
                {% endif %}
                <tbody>
                {% for user in users %}
                    <tr style="cursor: pointer"
                        onclick="window.location='{{ url_for('main.view_record', user_id=user.id) }}'">
                        <td>{{ user.id }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.first_name }}</td>
                        <td>{{ user.last_name }}</td>
                        <td>{{ user.contact_number }}</td>
                        <td>{{ user.job.job_title }}</td>
                        <td>{{ user.skill_1 }}</td>
                        <td>{{ user.skill_2 }}</td>
                        <td>{{ user.skill_3 }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}